/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnaSayfa.java
 *
 * Created on Oct 27, 2011, 11:34:20 PM
 */
package wsclient;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileFilter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author BSTNC
 */
public class AnaSayfa extends javax.swing.JFrame {

    /** Creates new form AnaSayfa */
    public AnaSayfa() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnFileSec = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtImageURL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKaydedilecekURL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbAlgoritma = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbthreshold = new javax.swing.JComboBox();
        lblThreLabel = new javax.swing.JLabel();
        txtThreDeger = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbScanType = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matlab Edge Detection v.1.1");

        jButton1.setText("Generate And Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel1.setText("!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel2.setText("!!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        btnFileSec.setText("Select  Image");
        btnFileSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileSecActionPerformed(evt);
            }
        });

        jLabel3.setText("Image URL :");

        txtImageURL.setEnabled(false);

        jLabel4.setText("Save To:");

        jLabel5.setText("Choose Algorithm:");

        cmbAlgoritma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sobel", "roberts", "prewitt", "canny" }));
        cmbAlgoritma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlgoritmaActionPerformed(evt);
            }
        });

        jLabel6.setText("Original Image ");

        jLabel8.setText("Edge Detected Image");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Threshold :");

        cmbthreshold.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manuel", "Auto" }));
        cmbthreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbthresholdActionPerformed(evt);
            }
        });

        lblThreLabel.setText("Threshold Value : ");

        txtThreDeger.setText("0.01");

        jLabel10.setText("Scan Type :  ");

        cmbScanType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Both", "Vertical", "Horizontal" }));
        cmbScanType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbScanTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThreLabel)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbScanType, 0, 124, Short.MAX_VALUE)
                    .addComponent(cmbthreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThreDeger, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap(103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbthreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThreLabel)
                    .addComponent(txtThreDeger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbScanType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cmbAlgoritma, 0, 231, Short.MAX_VALUE)
                                        .addComponent(txtKaydedilecekURL, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                                    .addComponent(txtImageURL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel7))
                            .addComponent(jLabel8)
                            .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(btnFileSec, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFileSec, saveButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtImageURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFileSec))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKaydedilecekURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cmbAlgoritma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String Algoritma = cmbAlgoritma.getSelectedItem().toString();
            String SecilenImage = txtImageURL.getText();
            String KaydedilcekImage = txtKaydedilecekURL.getText();
            String ThresholdState = cmbthreshold.getSelectedItem().toString();
            double thresholdValue = Double.valueOf(txtThreDeger.getText());
            String ScanType = cmbScanType.getSelectedItem().toString();

            EdgeDetection ed = new EdgeDetection();
            ed.MainEdgeDetectionMethod(Algoritma, SecilenImage, KaydedilcekImage, ThresholdState, thresholdValue, ScanType);

            try {
                Thread.sleep(3000);
            } catch (InterruptedException ex) {
                Logger.getLogger(AnaSayfa.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon2 = new ImageIcon(txtKaydedilecekURL.getText());
            icon2 = new ImageIcon(icon2.getImage().getScaledInstance(300, 300, BufferedImage.SCALE_SMOOTH));
            jLabel2.setIcon(icon2);
            jLabel2.setText("");
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null,e.getMessage(),"", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFileSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileSecActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("C:/");
        jfc.setFileFilter(new FileNameExtensionFilter("JPG Dosyaları", "jpg"));
        int kullaniciSecimi = jfc.showOpenDialog(null);
        if (kullaniciSecimi == JFileChooser.APPROVE_OPTION) {
            txtImageURL.setText(jfc.getSelectedFile().toString());
            ImageIcon icon = new ImageIcon(txtImageURL.getText());
            icon = new ImageIcon(icon.getImage().getScaledInstance(300, 300, BufferedImage.SCALE_SMOOTH));
            jLabel1.setIcon(icon);
            jLabel1.setText("");

        }



    }//GEN-LAST:event_btnFileSecActionPerformed

    private void cmbAlgoritmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlgoritmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAlgoritmaActionPerformed

    private void cmbthresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbthresholdActionPerformed
        // TODO add your handling code here:
        if (cmbthreshold.getSelectedItem().equals("Auto")) {
            lblThreLabel.setEnabled(false);
            txtThreDeger.setEnabled(false);
        } else {
            lblThreLabel.setEnabled(true);
            txtThreDeger.setEnabled(true);
        }
    }//GEN-LAST:event_cmbthresholdActionPerformed

    private void cmbScanTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbScanTypeActionPerformed
        // TODO add your handling code here:
//        if (cmbScanType.getSelectedItem().equals("Auto")) {
//            lblSelectDegree.setVisible(false);
//            cmbSelectDegree.setVisible(false);
//        }else {
//                        lblSelectDegree.setVisible(true);
//            cmbSelectDegree.setVisible(true);
//        }
    }//GEN-LAST:event_cmbScanTypeActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
// TODO add your handling code here:
    JFileChooser jfc = new JFileChooser("C:/");
    jfc.setFileFilter(new FileNameExtensionFilter("JPG Dosyaları", "jpg"));
    jfc.showSaveDialog(txtKaydedilecekURL);

    txtKaydedilecekURL.setText(jfc.getSelectedFile().toString() + ".jpg");

}//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AnaSayfa().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFileSec;
    private javax.swing.JComboBox cmbAlgoritma;
    private javax.swing.JComboBox cmbScanType;
    private javax.swing.JComboBox cmbthreshold;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblThreLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField txtImageURL;
    private javax.swing.JTextField txtKaydedilecekURL;
    private javax.swing.JTextField txtThreDeger;
    // End of variables declaration//GEN-END:variables
}
